# Generated by Django 4.0.8 on 2022-11-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('img', models.URLField()),
                ('seckey', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Universities',
        ),
    ]
